language: python
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "pypy"
install:
 - pip install --upgrade pip
 - pip install .[tests]
 - sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver
script:
 - flake8
 - nosetests -vv
